[resolvers.cloudflare-dot]
address = "1.1.1.1:853"
protocol = "dot"

[groups.cloudflare-blocklist]
type                = "response-blocklist-ip"
resolvers           = ["cloudflare-dot"]
blocklist-format    = "location"
blocklist           = [
  "6255148", # Europe
  "2017370", # Russia
  "7839805", # Melbourne
]
filter=true

[listeners.local-udp]
address = ":1153"
protocol = "udp"
resolver = "cloudflare-blocklist"

[listeners.local-tcp]
address = ":1153"
protocol = "tcp"
resolver = "cloudflare-blocklist"
