[resolvers.cloudflare-dot]
address = "1.1.1.1:853"
protocol = "dot"

[groups.cloudflare-blocklist]
type             = "response-blocklist-name"
resolvers        = ["cloudflare-dot"]
blocklist-format = "domain"
blocklist        = [
  'controlpanel.evil.com.',
  '*.acme.test',
]
#filter = true # Set to true if the response RRs should be filtered rather than returning NXDOMAIN (default)

[listeners.local-udp]
address = ":53"
protocol = "udp"
resolver = "cloudflare-blocklist"

[listeners.local-tcp]
address = ":53"
protocol = "tcp"
resolver = "cloudflare-blocklist"
